name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please provide as much detail as possible to help us resolve the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what went wrong
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please copy and paste any relevant log output
      placeholder: Paste logs here
      render: shell

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the software are you running?
      options:
        - main (latest)
        - v0.1.x
        - v0.2.x
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      multiple: true
      options:
        - Backend API
        - Frontend UI
        - Database
        - Zammad Connector
        - Kimai Connector
        - Sync Engine
        - Docker/Deployment
        - Other (please specify)
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where is this happening?
      options:
        - Development
        - Production
        - Docker Compose
        - Kubernetes
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, configuration, etc.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checks
      description: Please confirm the following
      options:
        - label: I have searched for existing issues
          required: true
        - label: I have included all relevant information
          required: true
        - label: I have checked the documentation
          required: true
