"""add already_synced and skipped to sync_run

Revision ID: 3f5d305feae7
Revises: ce97bf6a2f63
Create Date: 2025-11-10 01:29:13.751823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5d305feae7'
down_revision = 'ce97bf6a2f63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_runs', sa.Column('entries_already_synced', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('sync_runs', sa.Column('entries_skipped', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_runs', 'entries_skipped')
    op.drop_column('sync_runs', 'entries_already_synced')
    # ### end Alembic commands ###
